Import('RTT_ROOT')
Import('rtconfig')
from building import *
if GetDepend('RT_USING_USB_DEVICE') == True:
    cwd = GetCurrentDir()
    src = Glob('USB_DEV/*.c')
    src += Glob('USB_DEV/USB_MSC/*.c')
    CPPPATH = [cwd + '/USB_DEV/USB_MSC', cwd + '/USB_DEV']
    group = DefineGroup('USB_DEV', src, depend = [''], CPPPATH = CPPPATH)
    Return('group')

if GetDepend('RT_USING_USB_HOST') == True:
    cwd = GetCurrentDir()
    src = Glob('USB_HOST/*.c')
    src += Glob('USB_HOST/HID/*.c')
    CPPPATH = [cwd + '/USB_HOST/HID', cwd + '/USB_HOST']
    group = DefineGroup('USB_HOST', src, depend = [''], CPPPATH = CPPPATH)
    Return('group')