Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'USB_DEV')
src = Glob('*.c')
src += Glob('USB_MSC/*.c')

CPPPATH = [cwd + '/USB_MSC', cwd]

group = DefineGroup('USB_DEV', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

