Import('RTT_ROOT')
Import('rtconfig')
from building import *


cwd     = os.path.join(str(Dir('#')), 'USB_HOST')
src	= Glob('*.c')
src += Glob('USB_MSC/*.c')
CPPPATH = [cwd + '/HID', cwd]
group = DefineGroup('USB_HOST', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
# add USB related source code 
